  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend
    labels:
      app: backend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
        - name: backend
          image: sadiqmohamedamine/spring-ebanking:v1
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: DATABASE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: DATABASE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DATABASE_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: JWT_SECRET
